base/urls.py
# ready modules
from django.urls import URLPattern, path,include

# my modules
from base.views import *

app_name = 'post'

urlpatterns = [
    path("",homepage,name="home_url"),
    path("create/",createpage,name="create_url"),
    path("detail/<str:pk_slug_detail>/",detailpage,name="detail_url"),
    path("update/<str:pk_slug_update>",updatepage,name="update_url"),
    path("delete/<str:pk_slug_delete>",deletepage,name="delete_url"),
    
]

blog1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("base.urls"))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from ckeditor.fields import RichTextField

class Author(models.Model):
    firstname = models.CharField(max_length=200,blank=True,null=True)
    lastname = models.CharField(max_length=200,blank=True,null=True)
    age = models.IntegerField(blank=True,null=True)
    email = models.EmailField(max_length=200,blank=True,null=True)
    info = models.TextField(max_length=1000,blank=True,null=True)
    date_hired = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    profil_picture = models.ImageField(blank=True,null=True)

    def __str__(self):
        return self.firstname

class Tag(models.Model):
    name = models.CharField(max_length=200, blank=True,null=True)
    frequency = models.IntegerField(default=0,blank=True,null=True)

    def __str__(self):
        return self.name

class Post(models.Model):

    CATEGOIRES = (
    ("daily_news", "Daily News"),
    ("sports","Sports"),
    ("health","Health"),
    ("crypto","Cryptocurrencies"),
    )

    STATUS = (
        ("draft","Draft"),
        ("published","Published")
    )

    title = models.CharField(max_length=200,blank=True,null=True)
    content = RichTextField(max_length=5000,blank=True,null=True)
    status = models.CharField(max_length=200,choices=STATUS,null=True)
    category = models.CharField(max_length=200,null=True,choices = CATEGOIRES)
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author,blank=True,null=True,on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    date_updated = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    image_post = models.ImageField(blank=True,null=True)
    slug = models.SlugField(unique=True,editable=False,max_length=210)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:detail_url', kwargs={"pk_slug_detail":self.slug})

    def get_unique_slug(self):
        slug = slugify(self.title.replace('ı','i'))
        unique_slug = slug
        counter = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = "{}-{}".format(slug,counter)
            counter +=1
        return unique_slug 

    def save(self, *args, **kwargs):
        self.slug = self.get_unique_slug()
        return super(Post,self).save(*args,**kwargs)    

    class Meta:
        ordering = ('-date_created',)

base/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = "__all__"
        exclude =[ "slug"]
       

base/views.py
from turtle import title
from unicodedata import category
from django.shortcuts import redirect, render,get_object_or_404
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.db.models import Q

#my modules
from .models import Post
from .forms import PostForm
from .filters import PostFilter

def homepage(request):
    post_list = Post.objects.all()

    # query = request.GET
    # if query:
    #     post_list = post_list.filter(
    #         Q(title__icontains=query)|
    #         Q(content__icontains=query)|
    #         Q(author__firstname__icontains=query)|
    #         Q(author__lastname__icontains=query)|
    #         Q(category__icontains=query)|
    #         Q(tags__icontains=query)
    #     ).distinct()

    post_filter = PostFilter(request.GET,queryset=post_list)
    post_list = post_filter.qs

    paginator = Paginator(post_list,5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {"posts": posts}
    return render(request, 'base/index.html',context)


def createpage(request):
    form = PostForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        post = form.save()
        return redirect("post:home_url")
    context = {"form": form}
    return render(request, 'base/crudpages/post_create.html',context)


def updatepage(request,pk_slug_update):
    post = Post.objects.get(slug=pk_slug_update)
    form = PostForm(request.POST or None,request.FILES or None,instance=post)
    if form.is_valid():
        form.save()
        return redirect("post:home_url")
    context = {"form": form}
    return render(request, 'base/crudpages/post_update.html',context)


def deletepage(request,pk_slugt_delete):
    post = Post.objects.get(slug=pk_slugt_delete)
    if request.method == 'POST':
        post.delete()
        return redirect("post:home_url")
    context = {}
    return render(request, 'base/crudpages/post_delete.html',context)


def detailpage(request,pk_slug_detail):
    post = get_object_or_404(Post,slug = pk_slug_detail)
    context = {"post": post}
    return render(request, 'base/leftside/postdetail.html',context)

base/templates/base/base.html
{% include "base/navbar.html" %}

{% block content %}

{% endblock %}

{% include 'base/footer.html' %}

base/templates/base/crudpages/post_create.html
{% include "base/navbar.html" %}
{% load crispy_forms_tags %}

<section id="contentbody">
    <div class="container-fluid">
      <div class="row">
        <div class=" col-md-6 col-md-offset-3">
            <h1>CREATE A NEW POST</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                {{ form.media }}
                <input type="submit" value="Create">
            </form>
        </div>

      </div>
    </div>
  </section>

{% include 'base/footer.html' %}

base/templates/base/crudpages/post_delete.html
{% include "base/navbar.html" %}

<section id="contentbody">
    <div class="container">
      <div class="row">
        <div class="col">
            <table>
                <tr><td><h1>DO YOU WANT TO DELETE THIS POST?</h1></td></tr>
                <tr>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <td>
                            <input class="btn btn-danger" type="submit" value="DELETE">
                            <a class="btn btn-info" href="{% url 'post:home_url' %}">CANCEL</a>
                        </td>
                    </form>
                </tr>
            </table>
            
        </div>
      </div>
    </div>
  </section>

{% include 'base/footer.html' %}

base/templates/base/crudpages/post_update.html
{% include "base/navbar.html" %}


<section id="contentbody">
    <div class="container">
      <div class="row">
        <div class=" col-6">
            <h1>CREATE A NEW POST</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <table>
                        <tr>
                            <td>{{form.title.label}}</td>
                            <td>{{form.title}}</td>
                        </tr>
                        <tr>
                            <td>{{form.content.label}}</td>
                            <td>{{form.content}}</td>
                        </tr>
                        <tr>
                            <td>{{form.author.label}}</td>
                            <td>{{form.author}}</td>
                        </tr>
                        <tr>
                            <td>{{form.status.label}}</td>
                            <td>{{form.status}}</td>
                        </tr>
                        <tr>
                            <td>{{form.category.label}}</td>
                            <td>{{form.category}}</td>
                        </tr>
                        <tr>
                            <td>{{form.tags.label}}</td>
                            <td>{{form.tags}}</td>
                        </tr>
                    </table>
                <input type="submit" value="Create">
            </form>
        </div>
      </div>
    </div>
  </section>

{% include 'base/footer.html' %}

base/templates/base/footer.html
{% load static %}
<footer id="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="footer_inner">
            <p class="pull-left">Copyright &copy; 2014 ColorMag</p>
            <p class="pull-right">Developed By WpFreeware</p>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <script src="{% static 'js/jquery.min.js' %}"></script> 
  <script src="{% static 'js/bootstrap.min.js' %}"></script> 
  <script src="{% static 'js/wow.min.js' %}"></script> 
  <script src="{% static 'js/custom.js' %}"></script>
  </body>
  </html>

base/templates/base/index.html
{% extends "./base.html" %}

{% block content %}

<section id="contentbody">
  <div class="container">
    <div class="row">


      <!-- left side -->
      <!-- -------------------------------------------------------------------------------- -->
      <div class=" col-sm-12 col-md-6 col-lg-6">
        <div class="row">
          <div class="leftbar_content">
            
            <!-- Title -->
            <h2>The New Stuff</h2>
    
            <!-- Posts -->
            {% include 'base/leftside/postflow.html' %}
    
          </div>
        </div>
      </div>


      <!-- middle side -->
      <!-- -------------------------------------------------------------------------------- -->
      <div class="col-sm-6 col-md-2 col-lg-2">
        <div class="row">
          <div class="middlebar_content">
    
            <!-- Title -->
            <h2 class="yellow_bg">What's Hot</h2>
    
            <!-- What is Hot -->
            {% include "base/middleside/hotposts.html" %}
    
            <!-- Popular Categories -->
            {% include "base/middleside/popularcategories.html" %}
          
    
          </div>
        </div>
      </div>



      <!-- right side -->
      <!-- -------------------------------------------------------------------------------- -->
      <div class="col-sm-6 col-md-4 col-lg-4">
        <div class="row">
          <div class="rightbar_content">
    
            <!-- Featured stuff -->
            {% include "base/rightside/featuredposts.html" %}
    
            <!-- Popular Posts -->
            {% include "base/rightside/popularposts.html" %}
    
            <!-- Popular Tags -->
            {% include "base/rightside/populartags.html" %}
    
          </div>
        </div>
      </div>
      

    </div>
  </div>
</section>


{% endblock %}

base/templates/base/leftside/postdetail.html
{% include "base/navbar.html" %}
{% load static %}

<section id="contentbody">
  <div class="container">
    <div class="row">
      
      <div class=" col-sm-12 col-md-6 col-lg-6">
        <div class="row">
          <div class="leftbar_content">
            

            <div class="singlepost_area">
              <div class="singlepost_content"> 
                <a href="#" class="stuff_category">{{ post.category }}</a> 
                <span class="stuff_date">{{ post.date_created|date:"M" }} <strong>{{ post.date_created|date:"d" }}</strong></span>
                <h2><a href="#">{{ post.title }}</a></h2>

                {% if post.image_post %}
                  <img class="img-center" style="height: auto;width: 100%;" src="{{ post.image_post.url }}" alt="{{ post.title }}">
                {% endif %}

                <p>{{ post.content|safe }} </p>

                <!-- paginator -->
                <a href="#" class="btn btn-primary">Primary</a> <a href="#" class="btn btn-success">Success</a> <a href="#" class="btn btn-info">Info</a> <a href="#" class="btn btn-danger">Danger</a> <a href="#" class="btn yellow_btn">Yellow</a> <a href="#" class="btn blue_btn">Blue</a> <a href="#">link</a>
                <div class="singlepage_pagination"> <a class="previous_btn" href="#">Previous</a> <a class="next_btn" href="#">Next</a> </div>
                <div class="social_area wow fadeInLeft">
                  <ul>
                    <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                    <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                    <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                    <li><a href="#"><span class="fa fa-linkedin"></span></a></li>
                    <li><a href="#"><span class="fa fa-pinterest"></span></a></li>
                  </ul>
                </div>

                <!-- author -->
                <div class="author"> 
                  {% if post.author.profil_picture %}
                    <a href="#"><img src="{{ post.author.profil_picture.url }}" alt="{{ post.author.firstname }} {{ post.author.lastname }}">
                    </a>
                  {% endif %}
                  <div class="author_details">
                    <h3><a href="#">{{ post.author.firstname }} {{ post.author.lastname }}</a></h3>
                  </div>
                </div>

              </div>
            </div>
            
            <div class="similar_post_area">
              <h2>Similar Post You May Like <i class="fa fa-thumbs-o-up"></i></h2>

              <ul class="featured_nav similarpost_nav wow fadeInDown animated" style="visibility: visible; animation-name: fadeInDown;">

                <li> <a href="#" class="featured_img"><img alt="" src="{% static 'images/featured_img1.jpg' %}"></a>
                  <div class="featured_title"> <a href="#" class="">Sed luctus semper odio aliquam rhoncus</a> </div>
                </li>

              </ul>

            </div>
          </div>
        </div>
      </div>

      <!-- middle side -->
      <!-- -------------------------------------------------------------------------------- -->
      <div class="col-sm-6 col-md-2 col-lg-2">
        <div class="row">
          <div class="middlebar_content">
    
            <!-- Title -->
            <h2 class="yellow_bg">What's Hot</h2>
    
            <!-- What is Hot -->
            {% include "base/middleside/hotposts.html" %}
    
            <!-- Popular Categories -->
            {% include "base/middleside/popularcategories.html" %}
          
    
          </div>
        </div>
      </div>



      <!-- right side -->
      <!-- -------------------------------------------------------------------------------- -->
      <div class="col-sm-6 col-md-4 col-lg-4">
        <div class="row">
          <div class="rightbar_content">
    
            <!-- Featured stuff -->
            {% include "base/rightside/featuredposts.html" %}
    
            <!-- Popular Posts -->
            {% include "base/rightside/popularposts.html" %}
    
            <!-- Popular Tags -->
            {% include "base/rightside/populartags.html" %}
    
          </div>
        </div>
      </div>



    </div>
  </div>
</section>

{% include 'base/footer.html' %}

base/templates/base/leftside/postflow.html
{% load static %}

{% for post in posts %}

<div class="single_stuff wow fadeInDown">
  <div class="single_stuff_img"> <a href="{{ post.get_absolute_url }}">

    {% if post.image_post %}
    <img class="img-fluid"style="height: auto;width: 100%;" src="{{ post.image_post.url }}" alt="{{ post.title }}"></a> 
    {% endif %}
  </div>
  <div class="single_stuff_article">
    <div class="single_sarticle_inner"> <a class="stuff_category" href="#">{{ post.category }}</a>
      <div class="stuff_article_inner"> 
        <span class="stuff_date">{{ post.date_created|date:"M" }} <strong>{{ post.date_created|date:"d" }}</strong></span>
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p>{{ post.content|safe|truncatechars:60 }}</p>
      </div>
      <div>
        <a class="btn btn-info" href="{% url 'post:update_url' post.id %}">UPDATE</a>
        <a class="btn btn-danger" href="{% url 'post:delete_url' post.id%}">DELETE</a>
      </div>
    </div>
  </div>

</div>

{% endfor %}
<!-- <div class="pagination ">
  <span class="step-links">
      {% if posts.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ posts.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
          Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
      </span>

      {% if posts.has_next %}
          <a href="?page={{ posts.next_page_number }}">next</a>
          <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div> -->

<div class="stuffpost_paginatinonarea wow slideInLeft pagination">
  <ul class="newstuff_pagnav step-links">
    {% if posts.has_previous %}
      <li>
        <a href="?page=1">&laquo; First</a>
      </li>
      <li>
        <a href="?page={{ posts.previous_page_number }}">Previous</a>
      </li> 
    {% endif %}
    <span class="current active_page">
      <!-- <li>
        Page {{ posts.number }} of {{ posts.paginator.num_pages }}
      </li> -->
    </span>
    
    <span>

      {% if posts.has_previous %}
      <li>
        <a href="?page={{ posts.paginator.num_pages }}">{{ posts.previous_page_number }}&q={{ request.GET.q }}</a>
      </li>
      {% endif %}
      <li>
        <a class="current active_page" href="?page={{ posts.number }}">{{ posts.number }}</a>
      </li>
      {% if posts.has_next %}
      <li>
        <a href="?page={{ posts.next_page_number }}">{{ posts.next_page_number }}&q={{ request.GET.q }}</a>
      </li>
      {% endif %}
     
    </span>

    {% if posts.has_next %}
      <li>
        <a href="?page={{ posts.next_page_number }}">Next</a>
      </li>
      <li>
        <a href="?page={{ posts.paginator.num_pages }}">Last &raquo;</a>
      </li>
    {% endif %}

    <!-- <li><a class="active_page" href="#">1</a></li>
    <li><a href="#">2</a></li> -->
  </ul>
</div>

base/templates/base/middleside/hotposts.html
{% load static %}

<div class="middlebar_content_inner wow fadeInUp">
    <ul class="middlebar_nav">
      <li> <a class="mbar_thubnail" href="#"><img src="{% static 'images/hot_img1.jpg' %}" alt=""></a> <a class="mbar_title" href="#">Sed luctus </a> </li>
      <li> <a class="mbar_thubnail" href="#"><img src="{% static 'images/hot_img1.jpg' %}" alt=""></a> <a class="mbar_title" href="#">Sed luctus</a> </li>
      <li> <a class="mbar_thubnail" href="#"><img src="{% static 'images/hot_img1.jpg' %}" alt=""></a> <a class="mbar_title" href="#">Sed luctus</a> </li>
    </ul>
  </div>

base/templates/base/middleside/popularcategories.html
<div class="popular_categori  wow fadeInUp">
    <h2 class="limeblue_bg">Most Popular Categories</h2>
    <ul class="poplr_catgnva">
      <li><a href="#">Business</a></li>
      <li><a href="#">Gallery</a></li>
      <li><a href="#">Life &amp; Style</a></li>
      <li><a href="#">Games</a></li>
      <li><a href="#">Slider</a></li>
      <li><a href="#">Sports</a></li>
    </ul>
  </div>

base/templates/base/navbar.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<title>ColorMag</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- fonts -->
<style>
  @font-face {
  font-family: 'Varela';
  font-style: normal;
  font-weight: 400;
  src: local('Varela'), url('{% static "fonts/Varela-400.woff" %}') format('woff');
  }

  @font-face {
    font-family: 'Eddie';
    src: url('{% static "fonts/Eddie.eot?#iefix" %}') format('embedded-opentype'), 
    url('{% static "fonts/Eddie.woff" %}') format('woff'),
    url('{% static "fonts/Eddie.ttf" %}')  format('truetype'),
    url('{% static "fonts/Eddie.svg#Eddie" %}') format('svg');
    font-weight: normal;
    font-style: normal;
  }
</style>
  
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}">
<link rel="stylesheet" href="{% static 'css/animate.css' %}">
<link rel="stylesheet" href="{% static 'css/structure.css' %}">
<!--[if lt IE 9]>
<script src="assets/js/html5shiv.min.js"></script>
<script src="assets/js/respond.min.js"></script>
<![endif]-->
</head>
<body>
<div id="preloader">
  <div id="status">&nbsp;</div>
</div>
<a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
<header id="header">
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          
          <!-- Homepage button-->
          <a class="navbar-brand" href="{% url 'post:home_url' %}"><span>My</span>Blog</a> 
        </div>

        <!-- menu -->
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav custom_nav">
            <li class=""><a href="index.html">Home</a></li>
            <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories</a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Daily News</a></li>
                <li><a href="#">Sports</a></li>
                <li><a href="#">Health</a></li>
                <li><a href="#">Cryptocurrencies</a></li>
              </ul>
            </li>
            <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Authors</a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Jon Olan</a></li>
                <li><a href="#">Mikel Oliver</a></li>
                <li><a href="#">John Zihnman</a></li>
              </ul>
            </li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">Advertising</a></li>
            <!-- for development -->
            <li><a href="{% url 'post:create_url' %}">Create</a></li>

          </ul>
        </div>
      </div>
    </nav>

    <!-- <nav id="searchForm" class="navbar navbar-light bg-light">
      <form class="form-inline" method="GET">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <input type="submit" value="S">
      </form>
    </nav> -->

    <form id="searchForm" method="GET">
      <input type="text" placeholder="Search...">
    </form>

  </div>
</header>

base/templates/base/rightside/featuredposts.html
{% load static %}

<div class="single_blog_sidebar wow fadeInUp">
    <h2>The Featured Stuff</h2>
    <ul class="featured_nav">

      <li> <a class="featured_img" href="#"><img src="{% static 'images/featured_img1.jpg' %}" alt=""></a>
        <div class="featured_title"> <a class="" href="#">Sed luctus semper odio aliquam rhoncus</a> </div>
      </li>

    </ul>
  </div>

  

base/templates/base/rightside/popularposts.html
{%  load static %}

<div class="single_blog_sidebar wow fadeInUp">
    <h2>Popular Posts</h2>
    <ul class="middlebar_nav wow">
      <li> <a href="#" class="mbar_thubnail"><img alt="" src="{% static 'images/hot_img1.jpg' %}"></a> <a href="#" class="mbar_title">Sed luctus semper odio aliquam rhoncus</a> </li>
      <li> <a href="#" class="mbar_thubnail"><img alt="" src="{% static 'images/hot_img1.jpg' %}"></a> <a href="#" class="mbar_title">Sed luctus semper odio aliquam rhoncus</a> </li>
    </ul>
  </div>

base/templates/base/rightside/populartags.html
<div class="single_blog_sidebar wow fadeInUp">
    <h2>Popular Tags</h2>
    <ul class="poplr_tagnav">
      <li><a href="#">Arts</a></li>
      <li><a href="#">Games</a></li>
      <li><a href="#">Nature</a></li>
      <li><a href="#">Comedy</a></li>
      <li><a href="#">Sports</a></li>
      <li><a href="#">Tourism</a></li>
      <li><a href="#">Videos</a></li>
    </ul>
  </div>